### ISSUE TITLE
[Enhancement] Item filter for N number of conditions being true

### ISSUE THREAD

**Issue by dschu012** [planqi/slashdiablo-maphack#58]
it'd be nice to have a filter that could match if N statements are true. i.e. if I had `LIFE>10`, `STR>5`, and `DEX>5` and wanted to match an item if only 2 of these statements were true you'd have to write out all valid combinations
```
(LIFE>10 AND STR>5) OR (LIFE>10 AND DEX>5) OR (STR>5 AND DEX>5)
```
it'd be cool to be able to do something like
```
COUNT(2, LIFE>10, STR>5, DEX>5)
```
to say you wanted to match atleast 2 of those conditions.

**Comment by JimmyTheJ** [comment]
That sounds like a good idea and basically a better and more exact version of what I was trying to achieve with the combined stats list I made awhile ago.

Eg: STRDEX>10
