### ISSUE TITLE
[Feature Request] Auto show minimap and Missed BO alert.

### ISSUE THREAD

**Issue by BeLikeLeBron** [planqi/slashdiablo-maphack#71]
Just a couple of ideas that might work nicely for the community:

- Hit Tab automatically upon entering game to auto show mini-map so you don't have to do it manually every time.

- A "missed BO/ NO BO" feature that alerts after 10 seconds or so if you accidentally forgot to BO and start teleing, etc. This happens sometimes if characters stay on way point or if BO barb accidentally shouts + BC's but doesn't BO. It can probably just be a time based alert that checks for BO and if you don't have it active, it pops up just like the "BO expired" alert.

I think at one point or another we've all started killing monsters without having battle orders while thinking we do have it active.

**Comment by dschu012** [comment]
First one should be pretty easy. Just need to add a toggle and have it set 
```
*p_D2CLIENT_AutomapOn = true;
``
on game join if we want to show it. Second one sounds a bit tricky need to think of a good way to handle that.
