### ISSUE TITLE
In-game BH settings box "hidden"

### ISSUE THREAD

**Issue by Labarr** [planqi/slashdiablo-maphack#75]
Any way to make the BH window in-game relative to the current Diablo II window size? 

We are running into issues where users BH settings window is "hidden" due to them settings it at a position that is available in 1344x700 resolution, but when upgrading to the newer resolution of 1068x600, this position is now outside the Diablo II window

**Comment by MarcosT96** [comment]
That's right, of course, check the UI.ini file, there are the coordinates of the Maphack menu button.
