### ISSUE TITLE
Always show items on ground. 

### ISSUE THREAD

**Issue by prisoneer** [planqi/slashdiablo-maphack#84]
I was using Sting Maphack and it has the option to always show you the items dropped on the ground. It's like you have pressed ALT all the time and everything else was working fine - opening chests, speaking with NPCs, teleporting to different towns etc.
Is it possible to implement this feature in BH ?

**Comment by dschu012** [comment]
Some notes on how another maphack does it. 
https://github.com/jieaido/d2hackmap/blob/master/m_PermShowItem.h#L18
I think that is for 1.11b but not positive.

**Comment by prisoneer** [comment]
> Some notes on how another maphack does it.
> https://github.com/jieaido/d2hackmap/blob/master/m_PermShowItem.h#L18
> I think that is for 1.11b but not positive.

I think this is Sting's Maphack.
The executable is called d2hackmap.
