### ISSUE TITLE
Auto-tele not working?

### ISSUE THREAD

**Issue by MortimerMcMire** [planqi/slashdiablo-maphack#93]
I've noticed the auto-tele is included but all of the config features are commented out. Is that feature still functional in the latest editions?

**Comment by JimmyTheJ** [comment]
Auto-Tele is not permitted on slashdiablo as far as I'm aware.

**Comment by MortimerMcMire** [comment]
I don't play on slashdiablo but I suppose that would make sense why it's disabled in their branch of BH. I suppose that begs the question 'why is it included in the repo then'

**Comment by dschu012** [comment]
That is why it is there. The next zone lines.

**Comment by MortimerMcMire** [comment]
simple enough, thanks for the quick answer
